### ISSUE TITLE
returned an error

### ISSUE THREAD

**Issue by Vortecked** [satanic/Ghetto-OGU-Autobumper#1]
![image](https://user-images.githubusercontent.com/71997442/172993494-0e12e2af-e747-4f4e-91a3-07c8a5d29db1.png)

**Comment by satanic** [comment]
Do you use the editor in quick replies?
If so, disable that. If you can't use it at all then I'm as lost as you.

When released this worked & from testing it still does using Windows + Google Chrome.

**Comment by Vortecked** [comment]
ok i found the issue, i added a "close" command thinking that it would otherwise just keep opening tabs which would not be nice to my computer, but instead that just breaks the whole thing. good to know.

also as for looping, if you add a "times" command at the beginning and an "end" command at the end, it will loop the test for the specified number of times in the times command

**Comment by satanic** [comment]
I'm still using the same old .side file & has no issues. I don't know how you managed to break it however, this is an end user issue.
Not because my files are broken.
